# Generated by Django 5.2.6 on 2025-11-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_adminsettings_allow_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='boost_base_price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Base price per day for ad boosts (e.g., 0.50 = $0.50/day)', max_digits=10, verbose_name='Boost Base Price Per Day'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='boost_enabled',
            field=models.BooleanField(default=True, help_text='Enable ad boosting feature', verbose_name='Ad Boost Enabled'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='featured_base_price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.33, help_text='Base price per day for featured ads (e.g., 0.33 = $0.33/day)', max_digits=10, verbose_name='Featured Ad Base Price Per Day'),
        ),
    ]
