# Generated by Django 5.2.6 on 2025-11-26 10:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0003_alter_ad_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product name (e.g., "Featured Ad - 30 Days")', max_length=200)),
                ('product_type', models.CharField(choices=[('FEATURED', 'Featured Ad'), ('BOOST', 'Ad Boost'), ('MEMBERSHIP', 'Premium Membership'), ('RENEWAL', 'Ad Renewal')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Product description shown to users')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Duration in days for featured/boost products', null=True)),
                ('boost_multiplier', models.PositiveIntegerField(default=1, help_text='Multiplier for ad visibility (e.g., 10 = 10x more visible)', validators=[django.core.validators.MinValueValidator(1)])),
                ('stripe_product_id', models.CharField(blank=True, help_text='Stripe Product ID from Stripe Dashboard', max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID from Stripe Dashboard', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Product available for purchase')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Product',
                'verbose_name_plural': 'Payment Products',
                'ordering': ['sort_order', 'product_type', 'duration_days'],
                'indexes': [models.Index(fields=['product_type', 'is_active'], name='payments_pa_product_804bc4_idx'), models.Index(fields=['sort_order'], name='payments_pa_sort_or_2734d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(db_index=True, help_text='Stripe PaymentIntent ID', max_length=255, unique=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, help_text='Stripe Checkout Session ID (if using Checkout)', max_length=255, null=True, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, help_text='Stripe Charge ID', max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Actual amount paid', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method type (card, wallet, etc.)', max_length=50)),
                ('payment_date', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for payment failure')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount refunded', max_digits=10)),
                ('refund_reason', models.TextField(blank=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True, help_text='Stripe receipt URL')),
                ('invoice_url', models.URLField(blank=True, help_text='Stripe invoice URL')),
                ('applied_at', models.DateTimeField(blank=True, help_text='When the benefit was applied to the ad', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the benefit expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata')),
                ('ad', models.ForeignKey(blank=True, help_text='Ad this payment is for (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='ads.ad')),
                ('refunded_by', models.ForeignKey(blank=True, help_text='Admin who processed the refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who made the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product purchased', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentproduct')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_refund_id', models.CharField(help_text='Stripe Refund ID', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.CharField(choices=[('ADMIN_REQUESTED', 'Admin Requested'), ('CUSTOMER_REQUESTED', 'Customer Requested'), ('DUPLICATE', 'Duplicate Payment'), ('FRAUDULENT', 'Fraudulent'), ('OTHER', 'Other')], max_length=50)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes about refund')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(help_text='Payment being refunded', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
                ('processed_by', models.ForeignKey(help_text='Admin who processed this refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Refund',
                'verbose_name_plural': 'Payment Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(db_index=True, help_text='Stripe Event ID', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='Stripe event type (e.g., payment_intent.succeeded)', max_length=100)),
                ('payload', models.JSONField(help_text='Full event payload from Stripe')),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='payments_we_event_t_8f0131_idx'), models.Index(fields=['processed', '-created_at'], name='payments_we_process_fb4633_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdBoost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boost_multiplier', models.PositiveIntegerField(default=10, help_text='Visibility multiplier (e.g., 10 = 10x more visible)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When boost expires')),
                ('views_during_boost', models.PositiveIntegerField(default=0, help_text='Views received during boost period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(help_text='Ad being boosted', on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='ads.ad')),
                ('payment', models.ForeignKey(help_text='Payment for this boost', on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Ad Boost',
                'verbose_name_plural': 'Ad Boosts',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['ad', '-started_at'], name='payments_ad_ad_id_88ff09_idx'), models.Index(fields=['expires_at'], name='payments_ad_expires_842977_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_7a85fd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['ad', '-created_at'], name='payments_pa_ad_id_3ec7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-payment_date'], name='payments_pa_payment_60e7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['payment', '-created_at'], name='payments_pa_payment_1a68a2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_18b7ac_idx'),
        ),
    ]
